dist: trusty
sudo: required

language: go
go:
  - 1.9
services:
  - postgresql
addons:
  postgresql: "9.6"

before_install:
  # ginkgo golint dep migrate
  - make installtools
  - bash install-postgres-10.sh

before_script:
  - make setup NAME=vulcanize_private
  - make migrate NAME=vulcanize_private
  - make fixlibcrypto

script:
  - make test

notifications:
  email: false
